# Generated by Django 5.2.17 on 2026-10-09 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_usuario_rol_delete_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('rol', models.CharField(choices=[('Super Administrador', 'super administrador'), ('Administrador', 'administrador'), ('Gestor', 'gestor'), ('Residente', 'residente')], max_length=30)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('expira', models.DateTimeField()),
                ('usada', models.DateTimeField(blank=True, null=True)),
                ('revocada', models.BooleanField(default=False)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='core.condominio')),
                ('invitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones_enviadas', to='core.usuario')),
            ],
            options={
                'db_table': 'invitacion',
                'indexes': [models.Index(fields=['email'], name='invitacion_email_7c2f74_idx')],
            },
        ),
    ]
