# Generated by Django 5.2.17 on 2026-10-10 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_rol_delete_rol'),
        ('invitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='relacion',
            field=models.CharField(blank=True, choices=[('dueno', 'Dueño'), ('arrendatario', 'Arrendatario')], max_length=15),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='core.unidad'),
        ),
    ]
