# Generated by Django 5.2.17 on 2026-10-06 01:52

import core.models
import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'ciudades',
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255)),
                ('portada', models.ImageField(blank=True, upload_to='condominios/portadas/')),
                ('edificios', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condominios', to='core.ciudad')),
            ],
            options={
                'db_table': 'condominio',
            },
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.PositiveIntegerField()),
                ('frecuente', models.BooleanField(default=False)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='core.condominio')),
            ],
            options={
                'db_table': 'costo',
            },
        ),
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reservable', models.BooleanField(default=False)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_comunes', to='core.condominio')),
                ('costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_comunes', to='core.costo')),
            ],
            options={
                'verbose_name_plural': 'areas comunes',
                'db_table': 'area_comun',
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('numero_pisos', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)])),
                ('viviendas_por_piso', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('subterraneo', models.BooleanField(default=False)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios_set', to='core.condominio')),
            ],
            options={
                'db_table': 'edificio',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_revision', 'En revisión'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=15)),
                ('prioridad', models.CharField(blank=True, choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=5)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.DateTimeField(blank=True, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.condominio')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=core.models.ticket_archivo_path)),
                ('subido', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='core.ticket')),
            ],
            options={
                'db_table': 'ticket_archivo',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.PositiveSmallIntegerField()),
                ('posicion', models.PositiveSmallIntegerField()),
                ('numero_unidad', models.CharField(max_length=10)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.edificio')),
            ],
            options={
                'db_table': 'unidad',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('monto', models.PositiveIntegerField()),
                ('detalles', models.CharField(blank=True, max_length=255)),
                ('fecha_pago', models.DateField()),
                ('fecha_pagado', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('atrasado', 'Atrasado')], default='pendiente', max_length=10)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de débito'), ('credito', 'Tarjeta de crédito'), ('transferencia', 'Transferencia')], max_length=15)),
                ('costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.costo')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.unidad')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('patente_vehiculo', models.CharField(blank=True, max_length=10)),
                ('tiempo_llegada', models.DateTimeField(blank=True, null=True)),
                ('tiempo_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('check_in', 'Check-in'), ('check_out', 'Check-out')], default='pendiente', max_length=10)),
                ('condominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitados', to='core.condominio')),
                ('edificio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitados', to='core.edificio')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitados', to='core.unidad')),
            ],
            options={
                'db_table': 'invitado',
            },
        ),
        migrations.CreateModel(
            name='EspacioEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('residente', 'Residente'), ('visita', 'Visita')], max_length=10)),
                ('subterraneo', models.BooleanField(default=False)),
                ('ocupado', models.BooleanField(default=False)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacionamientos', to='core.condominio')),
                ('edificio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estacionamientos', to='core.edificio')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estacionamientos', to='core.unidad')),
            ],
            options={
                'db_table': 'espacio_estacionamiento',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('nombre2', models.CharField(blank=True, max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('apellido2', models.CharField(blank=True, max_length=30)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_path)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[core.validators.validar_rut])),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('condominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.condominio')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.rol', verbose_name='Rol')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='unidad',
            name='arrendatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_arrendadas', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='dueno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades_propias', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_creados', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reserva', models.CharField(choices=[('invitado', 'Invitado'), ('area_comun', 'Área común')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_reserva', models.DateTimeField()),
                ('fin_reserva', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('nombre_invitado', models.CharField(blank=True, max_length=100)),
                ('area_comun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='core.areacomun')),
                ('invitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservaciones', to='core.invitado')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='core.unidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='core.usuario')),
            ],
            options={
                'db_table': 'reservacion',
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pin', models.BooleanField(default=False)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='core.condominio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anuncios', to='core.usuario')),
            ],
            options={
                'db_table': 'anuncio',
                'ordering': ['-pin', '-creado'],
            },
        ),
        migrations.AddConstraint(
            model_name='edificio',
            constraint=models.UniqueConstraint(fields=('condominio', 'numero'), name='edificio_numero_unico_por_condominio'),
        ),
        migrations.AddConstraint(
            model_name='edificio',
            constraint=models.UniqueConstraint(fields=('condominio', 'nombre'), name='edificio_nombre_unico_por_condominio'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado'], name='pago_estado_e7b4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_pago'], name='pago_fecha_p_e0ee42_idx'),
        ),
        migrations.AddConstraint(
            model_name='espacioestacionamiento',
            constraint=models.UniqueConstraint(fields=('condominio', 'numero'), name='estacionamiento_numero_unico_por_condominio'),
        ),
        migrations.AddConstraint(
            model_name='unidad',
            constraint=models.UniqueConstraint(fields=('edificio', 'numero_unidad'), name='unidad_numero_unico_por_edificio'),
        ),
        migrations.AddConstraint(
            model_name='unidad',
            constraint=models.UniqueConstraint(fields=('edificio', 'piso', 'posicion'), name='unidad_posicion_unica_por_edificio'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado'], name='ticket_estado_880f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='reservacion',
            index=models.Index(fields=['estado'], name='reservacion_estado_537f77_idx'),
        ),
        migrations.AddIndex(
            model_name='reservacion',
            index=models.Index(fields=['fecha_reserva'], name='reservacion_fecha_r_2090fa_idx'),
        ),
    ]
