# Generated by Django 5.2.17 on 2026-10-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Super Administrador', 'super administrador'), ('Administrador', 'administrador'), ('Gestor', 'gestor'), ('Residente', 'residente')], default='Residente', verbose_name='Rol'),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
