# Generated by Django 5.2.17 on 2026-10-07 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.areacomun')),
            ],
            options={
                'db_table': 'horario_area_comun',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
