# Generated by Django 5.2.17 on 2026-10-08 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_horarioareacomun'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='dias_anticipacion_maxima',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='duracion_maxima',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='permite_reservas_consecutivas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='requiere_reserva',
            field=models.BooleanField(default=True),
        ),
    ]
