"""
Django settings for sol project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


#=============================================================================================================
# CONFIGURACIÓN GENERAL
#=============================================================================================================

SECRET_KEY = 'django-insecure-8*0riol)&(jsvjl*51_b1#!5cdg%7k8x^6+7hwusyl=3p)4+7hwusyl=3p)4+o='

DEBUG = True

ALLOWED_HOSTS = []


#=============================================================================================================
# APLICACIONES
#=============================================================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]


#=============================================================================================================
# MIDDLEWARE
#=============================================================================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'sol.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sol.wsgi.application'


#=============================================================================================================
# BASE DE DATOS
#=============================================================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


#=============================================================================================================
# VALIDACIÓN DE CONTRASEÑAS
#=============================================================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#=============================================================================================================
# INTERNACIONALIZACIÓN
#=============================================================================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


#=============================================================================================================
# ARCHIVOS ESTÁTICOS Y MULTIMEDIA
#=============================================================================================================

STATIC_URL = 'static/'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


#=============================================================================================================
# CONFIGURACIÓN DE CLAVES PRIMARIAS
#=============================================================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#=============================================================================================================
# AUTENTICACIÓN
#=============================================================================================================

LOGIN_URL = "/login/"


#=============================================================================================================
# CORREO ELECTRÓNICO - DESARROLLO LOCAL
#=============================================================================================================

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = "no-reply@saascondominio.local"